CREATE TABLE "episodes" (
  "episodeID" varchar GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "airDate" date,
  "episode" int
);

CREATE TABLE "colors" (
  "colorID" varchar PRIMARY KEY,
  "colorName" varchar,
  "colorHex" varchar
);

CREATE TABLE "episodeColors" (
  "paintingID" varchar,
  "colorID" varchar
);

CREATE TABLE "subjects" (
  "subjectID" varchar PRIMARY KEY,
  "subjectType" varchar
);

CREATE TABLE "episodeSubjects" (
  "episodeID" varchar,
  "subjectID" varchar
);

ALTER TABLE "episodes" ADD FOREIGN KEY ("episodeID") REFERENCES "episodeColors" ("paintingID");

ALTER TABLE "episodes" ADD FOREIGN KEY ("episodeID") REFERENCES "episodeSubjects" ("episodeID");

ALTER TABLE "subjects" ADD FOREIGN KEY ("subjectID") REFERENCES "episodeSubjects" ("subjectID");

ALTER TABLE "colors" ADD FOREIGN KEY ("colorID") REFERENCES "episodeColors" ("colorID");
